server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/caovan/tensquare_config.git #注意这里是uri,而不是url,直接地址访问，码云上要配置权限为公开
  rabbitmq:
    host: 192.168.217.136
  management: #暴露触发消息总线的地址
    endpoints:
      web:
        exposure:
          include: bus-refresh