server:
  port: 9003
spring:
  application:
    name: tensquare-qa
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tensquare_qa?characterEncoding=utf-8
      username: root
      password: 123456
    jpa:
      database: MySQL
      show‐sql: true