server:
  port: 9003
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      database: spitdb
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true