server:
  port: 9008
spring:
  application:
    name: tensquare_user
  redis:
    host: localhost
    password: 123456
  rabbitmq:
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true