server:
  port: 9005
spring:
  application:
    name: tensquare-gathering
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show‐sql: true
  redis:
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true